### ISSUE TITLE
Swtich/support aws-sdk-go-v2

### ISSUE THREAD

**Issue by xentek** [epsagon/epsagon-go#18]
Even though `aws-sdk-go-v2` is not yet at v1.0.0, many teams (including mine) have adopted this version of the library in favor of `aws-sdk-go`. 

It might be too early for `epsagon-go` to switch to this version of the library for it's official release,  but would you be open to creating a branch (or a new repository) that is tracking `aws-sdk-go-v2`?

I can possibly help with this effort, but wanted to get buy-in (and possibly direction) from the epsagon team before I forked and submitted a PR.

**Comment by xentek** [comment]
To add more color to this... Maybe what is really needed is just a wrapper for `aws-sdk-go-v2` which can possibly live along side this `github.com/epsagon/epsagon-go/wrappers/aws/aws-sdk-go/aws` in the official release.

Right now, I'm able to wrap my lambda handlers, but nothing else, lowering the utility of epsagon for my team.

**Comment by enoodle** [comment]
I think a second wrapper will be the best backward compatible solution. We will look into implementing it (you are welcome to contribute if you can as we are in holidays now)

**Comment by ranrib** [comment]
implemented by https://github.com/epsagon/epsagon-go/pull/38
