### ISSUE TITLE
No exception type in errors

### ISSUE THREAD

**Issue by henprtz** [epsagon/epsagon-go#25]

**Comment by ronyis** [comment]
Looks like all the exception detail is missing (at least for Lambda)

**Comment by MatejBalantic** [comment]
Hi all, any updates on this? we are still just seeing "Error Detected" as the title of the error in dashboards, which is pretty useless..

**Comment by ranrib** [comment]
Hi @MatejBalantic we tried to solve it in a workaround, but it didn't help. It got into our team's sprint so it will be available in the next couple weeks. Sorry for holding this one for long.

**Comment by MatejBalantic** [comment]
Thanks for the update 👍

**Comment by MatejBalantic** [comment]
Awesome, we'll integrate this today 👍
